### ISSUE TITLE
How to compute height given a specific element's height inside the iFrame

### ISSUE THREAD

**Issue by paulbors** [davidjbradshaw/iframe-resizer#144] opened 2015-01-24 00:35 UTC
Is there a way to have a custom method to compute the iFrame height given a particular's DOM element's CSS height attribute?

I'm asking because I run into a use-case where we have a single app in an iFrame and the height is returned as 0.

Below is the jsFiddle that demonstrates is:
http://jsfiddle.net/paulbors/n3abtczy/

**Comment by davidjbradshaw** [comment] 2015-01-24 00:44
That's an interesting question, Have you tried the different height calculation methods? The lowestElement one should do that ok, but can be slow in old IE.

One suggestion would be to have some CSS or JS that sets the body height to match the element.

**Comment by davidjbradshaw** [comment] 2015-01-24 00:45
The other option would be to fork the code and add your own custom height calculation method to look at that element.

**Comment by davidjbradshaw** [comment] 2015-01-24 00:45
Let me know if any of those ideas work for you.

**Comment by josephliao** [comment] 2015-01-24 20:53
Unfurtunily, there is no way to get this height value using dom elements in this iframe.  It has to be coculated from js.

----- Reply message -----

**Comment by davidjbradshaw** [comment] 2015-01-24 22:57
I think it is a CSS issue, try this.

    #eVIEW::after{
		clear: both;
		content: ' ';
		height: 1px;
		overflow: hidden;
		border:solid 1px transparent;
	}

**Comment by paulbors** [comment] 2015-01-26 16:05
It would be nice if the API would allow us to register a "callback" function to override the ones that computer the height inside the iFrame.

In the mid-time we'll try to use your CSS to see if it solves the problem. If that doesn't work, then I guess we'll have to fork the code and create our own function. That would suck since we'll freeze the version of the plugin and will not benefit from future releases that easily.

**Comment by davidjbradshaw** [comment] 2015-01-26 16:10
All the options are currently registered in the parent page and the height is measured in the child, so not that simple a change.

Did you try the lowestElement method yet?

**Comment by paulbors** [comment] 2015-01-26 16:31
Thanks for the quick reply David!

Yes, the problem is that the content of the iFrame happens to be a single page app with DIV panels that change in height and are always "hidden" by being shifted off the screen with a large negative value.

I've tried all the possible height calculation methods and none of them behave as they should.
I haven't yet tried your CSS fix as I need to place it inside the iFrame and that takes longer since we don't have direct control of that content.

With the lowestElement on and a border on the iFrame the pug-in runs into an infinite loop and keep increasing the height of the iFrame. You can see this behavior in the updated jsFiddle at:
http://jsfiddle.net/n3abtczy/1/

Just navigate to the Eligibility tab (the tallest one) and then select the Back button and watch the menu content keep increasing in size for ever.

The infinite loop under this condition is:
```
[iFrameSizer][copayCard] Parsed 925 HTML elements
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] LowestElement bottom position calculated in 2ms
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] Trigger event: mutationObserver: [object HTMLDivElement] attributes
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] Sending message to host page (copayCard:3865:300:mutationObserver)
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] Parsed 925 HTML elements
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] LowestElement bottom position calculated in 3ms
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] Trigger event: mutationObserver: [object HTMLDivElement] attributes
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] No change in size detected
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] Parsed 925 HTML elements
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] LowestElement bottom position calculated in 3ms
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] Trigger event: mutationObserver: [object HTMLDivElement] attributes
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] No change in size detected
(index):29 [iFrameSizer][Host page] Received: [iFrameSizer]copayCard:3865:300:mutationObserver
(index):29 [iFrameSizer][Host page] Checking height is in range 0-Infinity
(index):29 [iFrameSizer][Host page] Checking width is in range 0-Infinity
(index):29 [iFrameSizer][Host page] Requesting animation frame
(index):29 [iFrameSizer][Host page] IFrame (copayCard) height set to 3865px
iframeResizer.contentWindow.min.js:9 [iFrameSizer][copayCard] Trigger event cancelled: resize
h
```

**Comment by davidjbradshaw** [comment] 2015-01-26 16:54
The issue with constant resizing is caused by writing CSS that sets an element to always be bigger than the current viewport. You can overcome this by setting the tolerance option to whatever number each loop increase the size by. However, the better solution is to fix your CSS so that you not setting the size of the element to always be bigger than the page.

**Comment by davidjbradshaw** [comment] 2015-01-26 17:10
I'm going to close this, as I don't think the issue is with the library, but let me know how you get on.

**Closed by davidjbradshaw** 2015-01-26 17:10 UTC

**Comment by paulbors** [comment] 2015-01-26 17:55
Yes, using the tolerance in conjunction with the lowestElement method worked.

However that iFrame code is poorly written and it has other bugs that I am noticing now.
At least the size is adjusted correctly when the JavaScript in the iFrame itself works without errors.

That's on the iFrame developers to figure out.

**Comment by paulbors** [comment] 2015-01-26 18:37
Hey David,

I just realized that the lowerstElement method is not feasible for us.
It sets the height of the iframe to be constant with the tallest panel in the single page app.

Therefore we're back to square one where we need another method to compute the height based on an arbitrary element's height.

If I develop the new method and give you a push request would you review it and add it in?

**Comment by davidjbradshaw** [comment] 2015-01-26 21:08
Have your iFrame dev's not heard of `display:none` or `top:-99999px` for stuff they don't want to show on the page?

Not that keen on adding something no one else will ever use.

**Comment by paulbors** [comment] 2015-01-26 21:43
It's a legacy application.

I'll consider either forking and extending or attempt to use the manual size() function inside the content window.

**Comment by davidjbradshaw** [comment] 2015-01-26 22:36
Yeah switching auto resize off and then writing a function to watch the size of the element you interested in is I think your best option.

If you care about IE10 or less then a setTimeout function that checks if the height of your element has changed an calls `size()` should only be a few lines of code. My default for setTimeout is 32ms, as it is just under 2 frames at 60Hz, anything higher than that and the delay is noticeable to the user

If you don't care about IE you could set up a mutation observer of the element.

**Comment by davidjbradshaw** [comment] 2015-01-26 22:45
Something like this.

    var 
        $el = $('.eVIEW'),
        h1  = $el.height;

    setTimeout(function(){
        var h2 $el.height();
        if ( h1 !== h2 ) parentIFrame.size( h1 = h2 );
    },32);

**Comment by paulbors** [comment] 2015-01-27 14:51
I was thinking of a timed loop as well.

First we'll try to make the call from inside the iFrame given that single page app logic.
Then we'll try the timed loop, and finally we'll fork the project if needed be.

I'm sure we can put this ticket to a rest. Once of those solutions should work.

Thanks for all your help David!

**Comment by davidjbradshaw** [comment] 2015-08-09 08:24
Version 3 now has an option called taggedElement. Which allows you to place an element anywhere on the page and have the iFrame size to it's bottom edge.
