### ISSUE TITLE
iFrame height not always correct on iOS devices.

### ISSUE THREAD

**Issue by godsdog** [davidjbradshaw/iframe-resizer#830] opened 2020-06-25 14:57 UTC
Hello,

on iOS devices like iPad Air and iPhone XS the iframe height isn't correct. The height isn't set it falls back to our css height. Sometimes after reloading the page it is but not always. When you rotate the device, the height is correct.
On MAC Safari everything is fine. I can provide a link to our dev site (via email, the site is not yet published).

I saw multiple issues about this topic, non has a solution or got investigated further due to lack of inactivity.
We need this issue fixed soon!

**Comment by godsdog** [comment] 2020-06-26 13:04
Just to mentioned: On the iframed page we use the size method to send the correct height:
`if ('parentIFrame' in window) {
  parentIFrame.size(newHeight);
}`
Therefore on the parent page we use:
`autoResize: false,`

**Comment by HenLab** [comment] 2020-06-26 20:54
Same problem here. We need this issue fixed soon too!

**Comment by davidjbradshaw** [comment] 2020-06-27 18:16
I would welcome a PR if you work out what the issue is

**Comment by godsdog** [comment] 2020-06-29 14:10
Can you take a look to the ipad remote console?

1. Wrong height:
![debug-iframe-1](https://user-images.githubusercontent.com/4984883/86016299-e57c3b80-ba22-11ea-9b34-1cdc04272200.jpg)

2. Correct height after rotating the ipad:
![debug-iframe-2](https://user-images.githubusercontent.com/4984883/86016334-f5941b00-ba22-11ea-9a89-114edef932f7.jpg)

I am not sure where to start to investigate further.

**Comment by godsdog** [comment] 2020-06-30 12:50
We could fix it by using these lines on our iframed page:

```
        window.iFrameResizer = {
            onReady: function () {
                iframeResize(); // Our custom height calculation function
            }
        }
```

Our function "iframeResize()" then uses: `window.parentIFrame.size(height);  `

**Comment by davidjbradshaw** [comment] 2024-02-22 18:33
Looking at this again, my guess this was fixed by adding the `onReadyStateChange` event listener a while ago. So closing this issue for now, as it appears no ones else has had the same problem, but let me know if it is still an issue.

**Closed by davidjbradshaw** 2024-02-22 18:33 UTC
Labels: Help wanted
